# --------------------------------------------------------------------------
# Configuration of the parameters for training and preprocessing
# very-high resolution dataset using deep learning techniques.
# --------------------------------------------------------------------------

experiment_name: landcover-trees
experiment_type: landcover

data_dir: '/projects/kwessel4/nga-senegal/scripts/att/dataset'

seed: 42
gpu_devices: 0,1,2,3
mixed_precision: True
xla: False

input_bands:
  - CoastalBlue
  - Blue
  - Green
  - Yellow
  - Red
  - RedEdge
  - NIR1
  - NIR2

output_bands:
  - CoastalBlue
  - Blue
  - Green
  - Yellow
  - Red
  - RedEdge
  - NIR1
  - NIR2

mean:
  - 1
std:
  - 1

expand_dims: True
tile_size: 256
include_classes: True
augment: True
standardize: True
batch_size: 128
n_classes: 3
test_size: 0.20
learning_rate: 0.0001
max_epochs: 6000
patience: 10
loss: categorical_crossentropy

# window_size: 8192
window_size: 10000
pred_batch_size: 128
inference_overlap: 2
inference_treshold: 0.50

# Prediction location
model_filename: /projects/kwessel4/nga-senegal/scripts/att/dataset/model/63-0.13.hdf5
inference_regex: '/home/mle35/nga-senegal/scripts/att/test/*.tif'
inference_save_dir: /home/mle35/nga-senegal/scripts/att/dataset/predictions/63-0.13/images
