square_number: 29

algorithm: kmeans

input_txt_file: '/explore/nobackup/people/mwooten3/Senegal_LCLUC/selectTappan/ETZ_newTappan/Tappan29_WV-MS.txt'
input_identifier: '-toa.tif'

clip: True
upper_left_x: 456974
upper_left_y: 1651760
window_size_x: 5000
window_size_y: 5000

clustering: True
num_clusters: 60
random_state: 42
batch_size: 32

output_pre_str: 'Tappan'

output_dir: '/explore/nobackup/people/cssprad1/projects/3sl/code/development/kmeans_tappan/output/tappan_29'
