square_number: 26

algorithm: kmeans

input_txt_file: '/explore/nobackup/people/mwooten3/Senegal_LCLUC/selectTappan/CAS_newTappan/Tappan26_WV-MS.txt'
input_identifier: '-toa.tif'

clip: True
upper_left_x: 336974
upper_left_y: 1421760
window_size_x: 5000
window_size_y: 5000

clustering: True
num_clusters: 30
random_state: 42
batch_size: 64

output_pre_str: 'Tappan'

output_dir: '/explore/nobackup/people/cssprad1/projects/3sl/code/development/kmeans_tappan/output/tappan_26'
